gcloud run deploy test-adapter \
    --image=us.gcr.io/neuralnexus-467517/nn-avatar-adapter-management:latest \
    --service-account=cloud-run-deployer@neuralnexus-467517.iam.gserviceaccount.com \
    --region=us-central1 \
    --cpu=1 \
    --memory=2Gi \
    --max-instances=1 \
    --timeout=900 \
    --allow-unauthenticated \
    --set-env-vars=USER_ID=test-user,PYTHONUNBUFFERED=1 \
    --set-secrets=HF_TOKEN=HF_TOKEN:latest,AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:latest,AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest,AWS_REGION=AWS_REGION:latest,S3_BUCKET_NAME=S3_BUCKET_NAME:latest,APP_ENV=APP_ENV:latest,DEBUG=DEBUG:latest,CHROMA_PERSIST_DIRECTORY=CHROMA_PERSIST_DIRECTORY:latest,EMBEDDING_MODEL=EMBEDDING_MODEL:latest,MAX_BATCH_SIZE=MAX_BATCH_SIZE:latest \
    --project=neuralnexus-467517